-- AlterTable
ALTER TABLE `user` ADD COLUMN `cv` VARCHAR(191) NULL,
    ADD COLUMN `specialite` VARCHAR(191) NULL,
    ADD COLUMN `status` ENUM('PENDING', 'APPROVED', 'REJECTED') NOT NULL DEFAULT 'PENDING';
